"""PILOT-2A pilot2 package: data models + controlled vocabulary (DESIGN-ONLY intent).

Opt-in subpackage: NOT imported by the main ``aios`` package, so it never
affects production startup, migrations, or schema. Import explicitly via
``import aios.pilot2``.
"""
from aios.pilot2.attribution_head import (
    AttributionHeadError,
    current_decision,
    decision_history,
    finalize_attribution,
    replace_attribution,
    unattached_decisions,
)
from aios.pilot2.attribution_solver import (
    AttributionSolverError,
    finalize_solved,
    solve,
)
from aios.pilot2.models import (
    AttributionLevel,
    AttributionProposal,
    Channel,
    ClickEvent,
    CohortTag,
    ContentTaxonomyTerm,
    ExperimentRegistry,
    ExperimentStatus,
    FetchStatus,
    FinalAttributionDecision,
    FinalAttributionHead,
    MiheEndpoint,
    MiheSnapshot,
    Pilot2Base,
    Platform,
    PlatformMetricSnapshot,
    PublicationEvent,
    RegistrationAttributionLevel,
    RegistrationObservation,
    pilot2_metadata,
)
from aios.pilot2.owner_report import (
    DailyReport,
    build_daily_report,
    render_report_text,
)
from aios.pilot2.registration_diff import (
    MiheCustomer,
    MiheCustomerSnapshot,
    RegistrationDiffRow,
    SnapshotIncompleteError,
    SnapshotPaginationError,
    SnapshotReplayConflictError,
    SnapshotSequenceGapError,
    diff_registrations,
    persist_diffs,
    run_registration_diff,
    serialize_diffs,
)
from aios.pilot2.vocabulary import (
    CONTENT_TAXONOMY,
    CONTENT_TAXONOMY_VERSION,
    TaxonomyDimension,
    validate_content_record,
    validate_taxonomy,
)

__all__ = [
    "pilot2_metadata",
    "Pilot2Base",
    "MiheSnapshot",
    "PublicationEvent",
    "ClickEvent",
    "PlatformMetricSnapshot",
    "RegistrationObservation",
    "RegistrationDiffRow",
    "MiheCustomer",
    "MiheCustomerSnapshot",
    "SnapshotIncompleteError",
    "SnapshotSequenceGapError",
    "SnapshotPaginationError",
    "SnapshotReplayConflictError",
    "diff_registrations",
    "persist_diffs",
    "run_registration_diff",
    "serialize_diffs",
    "solve",
    "finalize_solved",
    "AttributionSolverError",
    "build_daily_report",
    "render_report_text",
    "DailyReport",
    "AttributionProposal",
    "FinalAttributionDecision",
    "FinalAttributionHead",
    "ContentTaxonomyTerm",
    "ExperimentRegistry",
    "MiheEndpoint",
    "FetchStatus",
    "Channel",
    "Platform",
    "CohortTag",
    "AttributionLevel",
    "RegistrationAttributionLevel",
    "ExperimentStatus",
    "AttributionHeadError",
    "finalize_attribution",
    "replace_attribution",
    "current_decision",
    "decision_history",
    "unattached_decisions",
    "CONTENT_TAXONOMY_VERSION",
    "TaxonomyDimension",
    "CONTENT_TAXONOMY",
    "validate_taxonomy",
    "validate_content_record",
]
